### ISSUE TITLE
editor panic on windows  github.com/readykit/gd.BelongsTo(...)

### ISSUE THREAD

**Issue by Bmixo** [readykit/gd#2]
after i change example.gdextension file  into this 
```
[configuration]

entry_symbol = "loadExtension"

[libraries]

windows.64 = "bin/example.so"
```

run godot.windows.tools.x86_64.exe . 

get result output

```
lookup _enter_tree false
lookup _input false
lookup _shortcut_input false
lookup _unhandled_input false
lookup _unhandled_key_input false
lookup _process false
lookup _physics_process false
lookup _ready true
ExtendedNode
Object
[Performance TextServerManager NavigationMeshGenerator ProjectSettings IP Geometry2D Geometry3D ResourceLoader ResourceSaver OS Engine ClassDB Marshalls TranslationServer Input InputMap EngineDebugger Time NativeExtensionManager ResourceUID WorkerThreadPool JavaClassWrapper JavaScript ThemeDB DisplayServer RenderingServer AudioServer PhysicsServer2D PhysicsServer3D NavigationServer2D NavigationServer3D XRServer CameraServer]
Scene is ready!
Hello World!
sin= 0.9974949866040544
rotation= 0
rotation= 3.140000104904175
position= {50 25}
position= {100 25}
{<nil> {0x7ffb78bceea8 2485739323648 {{} {} -1} {<nil>}}}
ERROR: Index p_screen = 1 is out of bounds (get_screen_count() = 1).
   at: DisplayServerWindows::window_set_current_screen (platform\windows\display_server_windows.cpp:823)
free &{0xc00005e060 2486104823552 {{} {} 0} {0xc0000200d8}}
<DisplayServer#2550136957>
lookup _draw false
```

but when i try to use godot editor to open the exaple project,the godot editor panic

```
free &{0xc000086098 0 {{} {} 0} {0xc000086068}}
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules\gltf\register_types.cpp:75)
WARNING: FBX file import is enabled in the project settings, but no FBX2glTF path is configured in the editor settings. FBX files will not be imported.
     at: _editor_init (modules\gltf\register_types.cpp:99)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ffb76200add]

goroutine 17 [running, locked to thread]:
github.com/readykit/gd.BelongsTo(...)
        C:/Users/Bmixo/Desktop/gd/extension.go:36
main.glob..func2(0x0)
        C:/Users/Bmixo/Desktop/gd/example/src/main.go:41 +0x1d
github.com/readykit/gd.(*extensionClassHandlerFor[...]).new(0xc00006a0c0, {0xc00006a0c0}, 0xc000059e00?)
        C:/Users/Bmixo/Desktop/gd/extension.go:220 +0x184
github.com/readykit/gd.(*extensionClassHandlerFor[...]).create(0xc00007de20?)
        C:/Users/Bmixo/Desktop/gd/extension.go:238 +0x26
github.com/readykit/gd.create_instance_func(...)
        C:/Users/Bmixo/Desktop/gd/callbacks.go:43
```

**Comment by Splizard** [comment]
thanks for reporting, this has been fixed
