### ISSUE TITLE
return string value  panic: toUnsafe: unsupported type string

### ISSUE THREAD

**Issue by Bmixo** [readykit/gd#4]
return value panic

gd.Scripting:
```
LogIn gd.Method `gd:"LogIn(userName,passWord) result"`
```

And go Go function method is:
 ```
func (h HelloWorld) LogIn(userName, passWord string) (result string) {
return "xxx"
}

```

```
Login asasas asasasas
panic: toUnsafe: unsupported type string

goroutine 17 [running, locked to thread]:
github.com/readykit/gd.toResult({0x7ffd950c6e80?, 0xc0000890c0?}, 0x0?)
        C:/Users/Bmixo/go/pkg/mod/github.com/readykit/gd@v0.0.0-20221013042627-e71ec44f2fa6/functions.go:943 +0x759
github.com/readykit/gd.(*unsafeExtensionServer).call(0x7ffd95075560?, 0x52340?, 0x1e, 0x1e60ffbff0, 0x7ffd94d47788?)
        C:/Users/Bmixo/go/pkg/mod/github.com/readykit/gd@v0.0.0-20221013042627-e71ec44f2fa6/export.go:341 +0x23f
github.com/readykit/gd.method_call_ptr(0x7ffd94d47618?, 0xc000086000?, 0x0?, 0xc000052301?)
        C:/Users/Bmixo/go/pkg/mod/github.com/readykit/gd@v0.0.0-20221013042627-e71ec44f2fa6/callbacks.go:81 +0xc3
```

**Comment by Splizard** [comment]
Thanks for reporting, I'll take a look this weekend and try to flesh out a more complete set of types that can be exported via `gd.Method`.

Do you have any feedback on the API design of `gd` and how extensions will be created/exported?
